export const productlistdata = [
	{
		id: 1,
		medicinename: "Lenovo 3rd Generation",
		productImage: "assets/img/products/stock-img-01.png",
		medicinetype: "PT001",
		medicinecategory: "Laptop",
		bottlecapacity: "Lenovo",
		price: "$12500.00",
		unit: "Pc",
		totalbottle: "100",
		createdate: "Arroon",
		img: "assets/img/users/user-30.jpg",
	},
	{
		id: 2,
		medicinename: "Bold V3.2",
		productImage: "assets/img/products/stock-img-06.png",
		medicinetype: "PT002",
		medicinecategory: "Electronics",
		bottlecapacity: "Bolt",
		price: "$1600.00",
		unit: "Pc",
		totalbottle: "140",
		createdate: "Kenneth",
		img: "assets/img/users/user-13.jpg",
	},
	{
		id: 3,
		medicinename: "Nike Jordan",
		productImage: "assets/img/products/stock-img-02.png",
		medicinetype: "PT003",
		medicinecategory: "Shoe",
		bottlecapacity: "Nike",
		price: "$6000.00",
		unit: "Pc",
		totalbottle: "780",
		createdate: "Gooch",
		img: "assets/img/users/user-11.jpg",
	},
	{
		id: 4,
		medicinename: "Apple Series 5 Watch",
		productImage: "assets/img/products/stock-img-03.png",
		medicinetype: "PT004",
		medicinecategory: "Electronics",
		bottlecapacity: "Apple",
		price: "$25000.00",
		unit: "Pc",
		totalbottle: "450",
		createdate: "Nathan",
		img: "assets/img/users/user-03.jpg ",
	},
	{
		id: 5,
		medicinename: "Amazon Echo Dot",
		productImage: "assets/img/products/stock-img-04.png",
		medicinetype: "PT005",
		medicinecategory: "Speaker",
		bottlecapacity: "Amazon",
		price: "$1600.00",
		unit: "Pc",
		totalbottle: "477",
		createdate: "Alice",
		img: "assets/img/users/user-02.jpg ",
	},
	{
		id: 6,
		medicinename: "Lobar Handy",
		productImage: "assets/img/products/stock-img-05.png",
		medicinetype: "PT006",
		medicinecategory: "Furnitures",
		bottlecapacity: "Woodmart",
		price: "$4521.00",
		unit: "Kg",
		totalbottle: "145",
		createdate: "Robb",
		img: "assets/img/users/user-5.jpg ",
	},
	{
		id: 7,
		medicinename: "Red Premium Handy",
		productImage: "assets/img/products/expire-product-01.png",
		medicinetype: "PT007",
		medicinecategory: "Bags",
		bottlecapacity: "Versace",
		price: "$2024.00",
		unit: "Kg",
		totalbottle: "747",
		createdate: "Steven",
		img: "assets/img/users/user-08.jpg ",
	},
	{
		id: 8,
		medicinename: "Iphone 14 Pro",
		productImage: "assets/img/products/expire-product-02.png",
		medicinetype: "PT008",
		medicinecategory: "Phone",
		bottlecapacity: "Iphone",
		price: "$1698.00",
		unit: "Pc",
		totalbottle: "897",
		createdate: "Gravely",
		img: "assets/img/users/user-04.jpg ",
	},
	{
		id: 9,
		medicinename: "Black Slim 200",
		productImage: "assets/img/products/expire-product-03.png",
		medicinetype: "PT009",
		medicinecategory: "Chairs",
		bottlecapacity: "Bently",
		price: "$6794.00",
		unit: "Pc",
		totalbottle: "741",
		createdate: "Kevin",
		img: "assets/img/users/user-01.jpg ",
	},
	{
		id: 10,
		medicinename: "Woodcraft Sandal",
		productImage: "assets/img/products/expire-product-04.png",
		medicinetype: "PT010",
		medicinecategory: "Bags",
		bottlecapacity: "Woodcraft",
		price: "$4547.00",
		unit: "Kg",
		totalbottle: "148",
		createdate: "Grillo",
		img: "assets/img/users/user-10.jpg ",
	},
];
