export const unitsdata = [
	{
		id: 1,
		serialno: 1,
		medicinename: "Piece",
		resemployee: "PC",
		lostquantity: "25",
		reason: "accident",
		date: "25 May 2023",
		status: "Active",
	},
	{
		id: 2,
		serialno: 2,
		medicinename: "Kilogram",
		resemployee: "KG",
		lostquantity: "15",
		reason: "accident",
		date: "24 Jun 2023",
		status: "Active",
	},
	{
		id: 3,
		serialno: 3,
		medicinename: "Gram",
		resemployee: "G",
		lostquantity: "47",
		reason: "accident",
		date: "23 Jul 2023",
		status: "Active",
	},
	{
		id: 4,
		serialno: 4,
		medicinename: "Meter",
		resemployee: "M",
		lostquantity: "28",
		reason: "accident",
		date: "22 Aug 2023",
		status: "Active",
	},
	{
		id: 5,
		serialno: 5,
		medicinename: "Liter",
		resemployee: "L",
		lostquantity: "47",
		reason: "accident",
		date: "21 Sep 2023",
		status: "Active",
	},
	{
		id: 6,
		serialno: 6,
		medicinename: "Kilo",
		resemployee: "K",
		lostquantity: "74",
		reason: "accident",
		date: "20 Sep 2023",
		status: "Active",
	},
];
